# Generated by Django 3.0.6 on 2020-06-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pienter', '0002_auto_20200621_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pien',
            field=models.IntegerField(default=0),
        ),
    ]
